source-academy/stories-backend

.github/workflows/ci.yml
Tests that the app compiles on every push.
Additional CI workflows such as linting, format checks, and tests will be added in the future.
=> Set up basic CI

.github/workflows/ci.yml, Makefile, README.md, hooks/pre-commit.sh, hooks/pre-push.sh
Ensures that, when installed, all pushed code passes format, lint, and test checks locally.
Also adds additional checks to the CI workflow.
=> Set up git hooks for linting and testing

internal/router/router.go, main.go
Refer to commit history for more details. Mainly includes minor fixes, as well as injection of Sentry's middleware into the router setup process.
=> Improve routing middleware

migrations/20230711155755-add_gorm_type_aliases.sql
Refer to the example given as a comment within the migration file itself on how to use.
=> Add GORM type aliases

controller/stories.go, controller/stories/stories.go, internal/router/router.go, model/stories.go, view/stories/view.go
* Refactor views and controllers into own packages
* Make requests handler names more generic/standardised
* Improves readability when reading the router configuration
=> Refactor stories View, Controller implementations

controller/json.go, controller/users.go, controller/users/users.go, internal/router/router.go, model/users.go, view/users/view.go
* Refactor views and controllers into own packages
* Make requests handler names more generic/standardised
* Improves readability when reading the router configuration
Also migrated the JSON encode logic to a separate file for better separation of logic across the files.
=> Refactor users View, Controller implementations

controller/users/users.go, model/users.go, params/users/create.go, view/users/list.go, view/users/view.go
Fixes some issues introduced in #28.
Part of #34.
=> Decouple and fix users' MVC pattern

deployment/api/Dockerfile, deployment/docker-compose.yml, deployment/migrator/Dockerfile, deployment/migrator/entrypoint.sh
Depends on #39 to be merged.
Currently, the DB is still not persisted when the Docker compose cluster is deleted. This is fine for staging purposes. In production, we will need to use Docker container volumes to persist the database. This will be done in a future PR.
Part of #52.
=> Set up deployment containers

.github/workflows/ci.yml, model/users_test.go, params/users/create_test.go
By no means exhaustive. Feel free to add more tests in a future PR.
~~Blocked by the lack of existence of a test DB in the CI environment.~~
Also updated the CI workflow following #39 to allow for a custom test DB name.
=> Create tests for users MVC

model/stories_test.go, model/users_test.go, params/stories/create_test.go
Most of the test are adapted and quite similar to #46.
But some tests are coupled, so they were commented out.
This is fine as we have plans to create our own internal test framework soon that will address the coupling issue. See #54 for more info on this.
=> Create tests for stories MVC

internal/database/errors_test.go, internal/database/middleware_test.go
* Tests for DB error handling
* Tests for DB middleware
=> Create tests for internal DB functions 

migrations/20230725191302-add-names-to-users.sql, model/users.go, params/users/create.go, view/users/view.go
Interim implementation while the notion of a "person" in #18 is yet to be implemented.
=> Add names to users

model/stories.go, view/stories/list.go, view/stories/view.go
Decided to not make use of nested objects to keep complexity minimal.
=> Return author name in story views

controller/stories/update.go, internal/router/router.go, model/stories.go, params/stories/create.go, params/stories/update.go, view/stories/list.go, view/stories/view.go
Refer to commit history for full details.
Some API changes:
* `storyId` &rarr; `id` in "single" view
* return ID in list view
=> Support updating of stories and improve API responses

deployment/.env.example, deployment/api/Dockerfile, deployment/docker-compose.yml, deployment/migrator/entrypoint.sh
* Adds missing required environment variables
* Fixes deployment server crash due to out of memory
* Fixes SSL validation not working
* Add explanatory comments where applicable
=> Fix deploy scripts

Makefile, internal/database/connect_test.go, internal/database/middleware_test.go, internal/testutils/testdb.go, internal/testutils/testutils.go, model/stories_test.go, model/users_test.go
> allow make test to specify a path
> rename variables
=> Refactor tests

.env.example, deployment/docker-compose.yml, internal/config/config.go, internal/router/router.go
=> Support configuring CORS rules via environment

internal/auth/context.go
It was resulting in errors in getting the user ID from the request context.
=> Fix get user ID from request context not working

internal/router/router.go
* Fix CORS error due to missing Authorization header (also allows credentials)
* Disable browser caching of responses
* Minor refactor/code quality improvements
=> Fix CORS error and add router improvements

internal/enums/groups/role.go
Simplifies unnecessary and/or redundant code. Also completes the TODO for creation of some validation method.
=> Simplify group roles

model/stories.go, model/stories_test.go
=> Fix `GroupID` field in Story model

deployment/backups.sh, deployment/docker-compose.yml, deployment/migrator/Dockerfile
Closes #52.
README/instructions are of lesser priority and will be added in the future.
=> Finalize deployment setup

controller/users/read.go, internal/usergroups/middleware.go, migrations/20230810152313-add_course_groups.sql, model/coursegroups.go, model/coursegroups_test.go, model/usergroups.go, model/usergroups_test.go, view/users/view.go, view/users/view_test.go
Adds the mapping between courses in the main backend to the groups in the stories backend.
=> Add course group mapping

controller/usergroups/create.go, internal/router/router.go, params/users/create.go, params/users/create_test.go
Code quality leaves a lot to be desired but:
* It works
* We are pressed for time to deploy MVP
* TODOs and FIXMEs for refactoring have been added
Part of #15.
=> Add roles to users' batch creation
